# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version: 2

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

builds:
  - binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/sapcc/go-api-declarations/bininfo.binName=git-cert-shim
      - -X github.com/sapcc/go-api-declarations/bininfo.version={{ .Version }}
      - -X github.com/sapcc/go-api-declarations/bininfo.commit={{ .FullCommit  }}
      - -X github.com/sapcc/go-api-declarations/bininfo.buildDate={{ .CommitDate }} # use CommitDate instead of Date for reproducibility
    main: ./cmd/git-cert-shim
    # Set the modified timestamp on the output binary to ensure that builds are reproducible.
    mod_timestamp: "{{ .CommitTimestamp }}"

release:
  make_latest: true
  prerelease: auto

snapshot:
  version_template: "{{ .Tag }}-next"
