# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "git-cert-shim"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/git-cert-shim"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "PROJECT",
  "VERSION",
  "hack/boilerplate.go.txt",
  "config/**",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/cert-manager/cert-manager/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-logr/logr/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/vault/api/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/onsi/ginkgo/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/onsi/gomega/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/pkg/errors/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_golang/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.uber.org/zap/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/k8s.io/api/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/apimachinery/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/client-go/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/controller-runtime/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/beorn7/perks/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/blang/semver/v4/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/cenkalti/backoff/v4/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/cespare/xxhash/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/davecgh/go-spew/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = [
  "vendor/github.com/emicklei/go-restful/v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/evanphx/json-patch/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/evanphx/json-patch/v5/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/fatih/color/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/fsnotify/fsnotify/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/fxamacker/cbor/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/go-jose/go-jose/v4/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-logr/zapr/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/jsonpointer/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/jsonreference/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-task/slim-sprig/v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/go-test/deep/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/gogo/protobuf/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/btree/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/gnostic-models/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/go-cmp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/gofuzz/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/pprof/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/uuid/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/errwrap/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-cleanhttp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-hclog/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-multierror/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-retryablehttp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-rootcerts/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-secure-stdlib/parseutil/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-secure-stdlib/strutil/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-sockaddr/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/hcl/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/josharian/intern/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/json-iterator/go/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/klauspost/compress/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/kr/pretty/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kr/text/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kylelemons/godebug/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/mailru/easyjson/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/mattn/go-colorable/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/mattn/go-isatty/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/mitchellh/go-homedir/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/mitchellh/mapstructure/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/modern-go/concurrent/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/modern-go/reflect2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/munnerz/goautoneg/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/pmezard/go-difflib/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/prashantv/gostub/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_model/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/common/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/procfs/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/rogpeppe/go-internal/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/ryanuber/go-glob/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/spf13/pflag/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/stretchr/objx/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/stretchr/testify/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/x448/float16/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/automaxprocs/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/goleak/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/multierr/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/golang.org/x/net/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/oauth2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sync/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sys/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/term/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/text/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/time/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/tools/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gomodules.xyz/jsonpatch/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/google.golang.org/protobuf/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/check.v1/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/evanphx/json-patch.v4/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/inf.v0/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/k8s.io/apiextensions-apiserver/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/klog/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/kube-openapi/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/utils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/gateway-api/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/json/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/randfill/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/structured-merge-diff/v4/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/yaml/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"
