# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: git-cert-shim

# Labels to add to all resources and selectors.
commonLabels:
  app: git-cert-shim

resources:
- rbac
- controller
