apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- controller.yaml

secretGenerator:
- name: git-cert-shim
  literals:
  - GIT_REMOTE_URL="git@github.com:or/some.git"
  - GIT_API_TOKEN=""
  # Uncomment the following when using SSH.
  #- GIT_SSH_PRIVKEY_FILE="/git-cert-shim.key"
  #files:
  #- git-cert-shim.key=key.yaml

images:
- name: git-cert-shim
  newName: sapcc/git-cert-shim
  newTag: v1.0.0
