apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- controller.yaml

secretGenerator:
- literals:
  - GIT_REMOTE_URL="https://github.com/unkown.git"
  - GITHUB_API_TOKEN="unknown"
  name: git-cert-shim

images:
- name: git-cert-shim
  newName: keppel.eu-de-1.cloud.sap/ccloud/git-cert-shim
  newTag: v0.0.3
