# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: git-cert-shim
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: manager
        controlledResources:
          - cpu
          - memory
        maxAllowed:
          cpu: 1
          memory: 512Mi
        minAllowed:
          cpu: 50m
          memory: 50Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: git-cert-shim
