name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:

env:
  GOLANGCI_LINT_VERSION: v1.60.2

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}